# Register at https://openweathermap.org to get your API key
api_key = "0906e2a4bcc2f7b2a86a89db7816e363"

# This is for Montreal, find your city at https://openweathermap.org
# The id will be the last part of the URL
city_id = "2034937"

# Display settings
units = "metric"
display_symbol = "°C"